# Load Libraries

In [39]:
import pandas as pd
import numpy as np

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)
                           
import os

# Check Directories

In [8]:
print(os.getcwd())

c:\Users\alber\Documents\GitHub\TheBridge\SVL_DS_Marzo_TB\2-Data Analysis\2-Pandas\Ejercicios\material_extra

In [11]:
os.listdir('opendata')

['measures_csv', 'samplePoints.csv']

# Read Data

## Sample Info

In [14]:
df_sample = pd.read_csv("opendata/samplePoints.csv", sep=";")
df_sample.head()

,Code,Sample Point,Type,Territory,Municipality,XETRS89,YETRS89,ZETRS89,Water range,Water range type,Basin,Section,Subgroup
0,CT01,Piezómetro Malta,SONDEOS,Bizkaia,Gernika-Lumo,526442,4795580,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)
1,CT02,Piezómetro Marcos Ormaetxea,SONDEOS,Bizkaia,Gernika-Lumo,526505,4795747,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)#Aguas (Piezometría)
2,CT03,Piezómetro Txarterina,SONDEOS,Bizkaia,Gernika-Lumo,526205,4796170,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)
3,CT04,Piezómetro EuskoTren,SONDEOS,Bizkaia,Gernika-Lumo,526345,4795917,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)#Aguas (Piezometría)
4,CT05,Sondeo Eusko Trenbideak,SONDEOS,Bizkaia,Gernika-Lumo,526343,4795904,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)

In [16]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code              146 non-null    object
 1   Sample Point      146 non-null    object
 2   Type              146 non-null    object
 3   Territory         146 non-null    object
 4   Municipality      146 non-null    object
 5   XETRS89           146 non-null    int64
 6   YETRS89           146 non-null    int64
 7   ZETRS89           144 non-null    float64
 8   Water range       146 non-null    object
 9   Water range type  146 non-null    object
 10  Basin             146 non-null    object
 11  Section           146 non-null    object
 12  Subgroup          146 non-null    object
dtypes: float64(1), int64(2), object(10)
memory usage: 15.0+ KB

## Measurements

In [22]:
ls_csv = [x for x in os.listdir("opendata/measures_csv") if x[-4:] == ".csv"]
len(ls_csv)

117

In [29]:
pd.read_csv("opendata/measures_csv/ct03_measure_all.csv", encoding="latin1", sep=";")

,Sample Point Code,Date,Hour,Type,Subgroup,Parameter,Species,Operator,Value,Unit,Quality,Situation,Level,Depth
0,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Cloruro de vinilo,-,=,0.1,µg/l,NaN,-,-,0
1,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.2-Diclorobenceno=o-Diclorobenceno,-,<,500.0,ng/l,NaN,-,-,0
2,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Temperatura del agua,-,=,16.3,ºC,NaN,-,-,0
3,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Conductividad,-,=,1424.0,µS/cm,NaN,-,-,0
4,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Oxígeno disuelto,-,=,44.3,mg/l,NaN,-,-,0
5,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Triclorometano (cloroformo),-,<,0.5,µg/l,NaN,-,-,0
6,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Bromodiclorometano,-,<,0.5,µg/l,NaN,-,-,0
7,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Dibromoclorometano,-,<,0.5,µg/l,NaN,-,-,0
8,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Bromoformo-Tribromometano,-,<,0.5,µg/l,NaN,-,-,0
9,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.1 Dicloroeteno,-,<,0.5,µg/l,NaN,-,-,0
10,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Trans-1.2 Dicloroeteno,-,<,0.5,µg/l,NaN,-,-,0
11,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Cis-1.2 Dicloroeteno,-,=,1.0,µg/l,NaN,-,-,0
12,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Tricloroetileno,-,<,0.5,µg/l,NaN,-,-,0
13,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Tetracloroetileno (percloroetileno),-,<,0.5,µg/l,NaN,-,-,0
14,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.1.2.2 Tetracloroetano,-,<,0.5,µg/l,NaN,-,-,0
15,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.1.2 Tricloroetano,-,<,0.5,µg/l,NaN,-,-,0
16,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.1.1-Tricloroetano-Metilcloroformo,-,<,0.5,µg/l,NaN,-,-,0
17,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.2-Dicloroetano,-,<,0.5,µg/l,NaN,-,-,0
18,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Diclorometano,-,<,0.5,µg/l,NaN,-,-,0
19,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Tetracloruro de carbono,-,<,0.5,µg/l,NaN,-,-,0
20,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.2 Dicloropropano,-,<,0.5,µg/l,NaN,-,-,0
21,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Cis-1.3 Dicloropropeno,-,<,0.1,µg/l,NaN,-,-,0
22,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Trans-1.3 Dicloropropeno,-,<,0.1,µg/l,NaN,-,-,0
23,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Clorobenceno,-,<,0.5,µg/l,NaN,-,-,0
24,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.3-Diclorobenceno=m-Diclorobenceno,-,<,0.5,µg/l,NaN,-,-,0
25,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.4-Diclorobenceno=p-Diclorobenceno,-,<,0.5,µg/l,NaN,-,-,0
26,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.1 Dicloroetano,-,<,0.5,µg/l,NaN,-,-,0

In [30]:
ls_df_all = [pd.read_csv("opendata/measures_csv/" + csv, sep=";", encoding="latin1") for csv in ls_csv]
ls_df_all[0].head()

,Sample Point Code,Date,Hour,Type,Subgroup,Parameter,Species,Operator,Value,Unit,Quality,Situation,Level,Depth
0,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Cloruro de vinilo,-,=,0.1,µg/l,NaN,-,-,0
1,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.2-Diclorobenceno=o-Diclorobenceno,-,<,500.0,ng/l,NaN,-,-,0
2,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Temperatura del agua,-,=,16.3,ºC,NaN,-,-,0
3,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Conductividad,-,=,1424.0,µS/cm,NaN,-,-,0
4,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Oxígeno disuelto,-,=,44.3,mg/l,NaN,-,-,0

In [34]:
ls_len = [len(df) for df in ls_df_all]
print("Numero medio de filas: {:.0f}+-{:.0f}".format(np.mean(ls_len), np.std(ls_len)))

Numero medio de filas: 31+-21

In [35]:
df_all = pd.concat(ls_df_all)
df_all.shape

(3592, 14)

In [37]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3592 entries, 0 to 6
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sample Point Code  3592 non-null   object
 1   Date               3592 non-null   object
 2   Hour               3592 non-null   object
 3   Type               3592 non-null   object
 4   Subgroup           3592 non-null   object
 5   Parameter          3592 non-null   object
 6   Species            3592 non-null   object
 7   Operator           3592 non-null   object
 8   Value              3592 non-null   float64
 9   Unit               3592 non-null   object
 10  Quality            0 non-null      float64
 11  Situation          3592 non-null   object
 12  Level              3592 non-null   object
 13  Depth              3592 non-null   int64
dtypes: float64(2), int64(1), object(11)
memory usage: 420.9+ KB

# Merge Data

In [40]:
display("df_all", "df_sample")

df_all
   Sample Point Code        Date   Hour         Type               Subgroup  \
0               CT03  15/02/2022  14:40      SONDEOS  Aguas (Fisicoquímica)
1               CT03  15/02/2022  14:40      SONDEOS  Aguas (Fisicoquímica)
2               CT03  15/02/2022  14:40      SONDEOS  Aguas (Fisicoquímica)
3               CT03  15/02/2022  14:40      SONDEOS  Aguas (Fisicoquímica)
4               CT03  15/02/2022  14:40      SONDEOS  Aguas (Fisicoquímica)
..               ...         ...    ...          ...                    ...
2               ZA-6  03/03/2022  09:15  MANANTIALES  Aguas (Fisicoquímica)
3               ZA-6  03/03/2022  09:15  MANANTIALES  Aguas (Fisicoquímica)
4               ZA-6  03/03/2022  09:15  MANANTIALES  Aguas (Fisicoquímica)
5               ZA-6  03/03/2022  09:15  MANANTIALES  Aguas (Fisicoquímica)
6               ZA-6  03/03/2022  09:15  MANANTIALES  Aguas (Fisicoquímica)

                              Parameter Species Operator     Value   Unit  \
0                     Cloruro de vinilo       -        =     0.100   µg/l
1   1.2-Diclorobenceno=o-Diclorobenceno       -        <   500.000   ng/l
2                  Temperatura del agua       -        =    16.300     ºC
3                         Conductividad       -        =  1424.000  µS/cm
4                      Oxígeno disuelto       -        =    44.300   mg/l
..                                  ...     ...      ...       ...    ...
2                         Conductividad       -        =   815.000  µS/cm
3                           Ortofosfato       -        <     0.031   mg/l
4                               Nitrito       -        <     0.020   mg/l
5                                Amonio       -        <     0.064   mg/l
6                               Nitrato       -        =    90.000   mg/l

    Quality Situation Level  Depth
0       NaN         -     -      0
1       NaN         -     -      0
2       NaN         -     -      0
3       NaN         -     -      0
4       NaN         -     -      0
..      ...       ...   ...    ...
2       NaN         -     -      0
3       NaN         -     -      0
4       NaN         -     -      0
5       NaN         -     -      0
6       NaN         -     -      0

[3592 rows x 14 columns]

df_sample
     Code                 Sample Point         Type    Territory  \
0    CT01             Piezómetro Malta      SONDEOS      Bizkaia
1    CT02  Piezómetro Marcos Ormaetxea      SONDEOS      Bizkaia
2    CT03        Piezómetro Txarterina      SONDEOS      Bizkaia
3    CT04         Piezómetro EuskoTren      SONDEOS      Bizkaia
4    CT05      Sondeo Eusko Trenbideak      SONDEOS      Bizkaia
..    ...                          ...          ...          ...
141  ZA-1          La Parra (Pozo CHE)      SONDEOS  Araba/Álava
142  ZA-2              Quiñones (ZA-2)      SONDEOS  Araba/Álava
143  ZA-3                Madero (ZA-3)      SONDEOS  Araba/Álava
144  ZA-4              El Campo (ZA-4)      SONDEOS  Araba/Álava
145  ZA-6            La Pauleja (ZA-6)  MANANTIALES  Araba/Álava

     Municipality  XETRS89  YETRS89  ZETRS89                 Water range  \
0    Gernika-Lumo   526442  4795580      0.0                     Gernika
1    Gernika-Lumo   526505  4795747      0.0                     Gernika
2    Gernika-Lumo   526205  4796170      0.0                     Gernika
3    Gernika-Lumo   526345  4795917      0.0                     Gernika
4    Gernika-Lumo   526343  4795904      0.0                     Gernika
..            ...      ...      ...      ...                         ...
141      Zambrana   509048  4722825      0.0  Aluvial de Miranda de Ebro
142      Zambrana   509634  4722733      0.0  Aluvial de Miranda de Ebro
143      Zambrana   510026  4722855      0.0         Sierra de Cantabria
144      Zambrana   509743  4722520      0.0  Aluvial de Miranda de Ebro
145      Zambrana   510379  4723404      0.0        Sinclinal de Trebiño

    Water range type Basin                                            Section  \
0       No aplicable   Oka         Zona drenante a Oka Interior - Oligohalino
1       No aplicable   Oka         Zona drenante a Oka Interior - Oligohalino
2       No aplicable   Oka         Zona drenante a Oka Interior - Oligohalino
3       No aplicable   Oka         Zona drenante a Oka Interior - Oligohalino
4       No aplicable   Oka         Zona drenante a Oka Interior - Oligohalino
..               ...   ...                                                ...
141     No aplicable  Ebro  Zona drenante a Río Ebro desde el río Zadorra ...
142     No aplicable  Ebro  Zona drenante a Río Ebro desde el río Zadorra ...
143     No aplicable  Ebro  Zona drenante a Río Ebro desde el río Zadorra ...
144     No aplicable  Ebro  Zona drenante a Río Ebro desde el río Zadorra ...
145     No aplicable  Ebro  Zona drenante a Río Ebro desde el río Zadorra ...

                                      Subgroup
0                        Aguas (Fisicoquímica)
1    Aguas (Fisicoquímica)#Aguas (Piezometría)
2                        Aguas (Fisicoquímica)
3    Aguas (Fisicoquímica)#Aguas (Piezometría)
4                        Aguas (Fisicoquímica)
..                                         ...
141                      Aguas (Fisicoquímica)
142                      Aguas (Fisicoquímica)
143                      Aguas (Fisicoquímica)
144                      Aguas (Fisicoquímica)
145                      Aguas (Fisicoquímica)

[146 rows x 13 columns]

In [41]:
print(df_all.columns)
print(df_sample.columns)

Index(['Sample Point Code', 'Date', 'Hour', 'Type', 'Subgroup', 'Parameter',
       'Species', 'Operator', 'Value', 'Unit', 'Quality', 'Situation', 'Level',
       'Depth'],
      dtype='object')
Index(['Code', 'Sample Point', 'Type', 'Territory', 'Municipality', 'XETRS89',
       'YETRS89', 'ZETRS89', 'Water range', 'Water range type', 'Basin',
       'Section', 'Subgroup'],
      dtype='object')

In [42]:
df_all_merged = pd.merge(df_all, df_sample, left_on="Sample Point Code", right_on="Code", how="left")
df_all_merged.head()

,Sample Point Code,Date,Hour,Type_x,Subgroup_x,Parameter,Species,Operator,Value,Unit,...,Territory,Municipality,XETRS89,YETRS89,ZETRS89,Water range,Water range type,Basin,Section,Subgroup_y
0,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Cloruro de vinilo,-,=,0.1,µg/l,...,Bizkaia,Gernika-Lumo,526205.0,4796170.0,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)
1,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),1.2-Diclorobenceno=o-Diclorobenceno,-,<,500.0,ng/l,...,Bizkaia,Gernika-Lumo,526205.0,4796170.0,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)
2,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Temperatura del agua,-,=,16.3,ºC,...,Bizkaia,Gernika-Lumo,526205.0,4796170.0,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)
3,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Conductividad,-,=,1424.0,µS/cm,...,Bizkaia,Gernika-Lumo,526205.0,4796170.0,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)
4,CT03,15/02/2022,14:40,SONDEOS,Aguas (Fisicoquímica),Oxígeno disuelto,-,=,44.3,mg/l,...,Bizkaia,Gernika-Lumo,526205.0,4796170.0,0.0,Gernika,No aplicable,Oka,Zona drenante a Oka Interior - Oligohalino,Aguas (Fisicoquímica)

In [49]:
print(df_all_merged.shape[0] >= df_all.shape[0])
print(df_all_merged.shape[0] == df_all.shape[0])

True
True

In [50]:
df_all_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3592 entries, 0 to 3591
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sample Point Code  3592 non-null   object
 1   Date               3592 non-null   object
 2   Hour               3592 non-null   object
 3   Type_x             3592 non-null   object
 4   Subgroup_x         3592 non-null   object
 5   Parameter          3592 non-null   object
 6   Species            3592 non-null   object
 7   Operator           3592 non-null   object
 8   Value              3592 non-null   float64
 9   Unit               3592 non-null   object
 10  Quality            0 non-null      float64
 11  Situation          3592 non-null   object
 12  Level              3592 non-null   object
 13  Depth              3592 non-null   int64
 14  Code               3576 non-null   object
 15  Sample Point       3576 non-null   object
 16  Type_y             3576 non-null   object
 17  Territory          3576 non-null   object
 18  Municipality       3576 non-null   object
 19  XETRS89            3576 non-null   float64
 20  YETRS89            3576 non-null   float64
 21  ZETRS89            3576 non-null   float64
 22  Water range        3576 non-null   object
 23  Water range type   3576 non-null   object
 24  Basin              3576 non-null   object
 25  Section            3576 non-null   object
 26  Subgroup_y         3576 non-null   object
dtypes: float64(5), int64(1), object(21)
memory usage: 785.8+ KB

In [51]:
df_all_merged[df_all_merged["Municipality"].isnull()]

,Sample Point Code,Date,Hour,Type_x,Subgroup_x,Parameter,Species,Operator,Value,Unit,...,Territory,Municipality,XETRS89,YETRS89,ZETRS89,Water range,Water range type,Basin,Section,Subgroup_y
2519,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Temperatura del agua,-,=,13.000,ºC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2520,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Amonio,-,<,0.064,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2521,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Nitrito,-,<,0.020,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2522,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Nitrato,-,=,69.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2523,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Bicarbonatos,-,=,300.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2524,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Carbonatos,-,<,1.200,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2525,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Sulfatos,-,=,150.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2526,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Cloruros,-,=,24.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Magnesio,-,=,31.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2528,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Calcio,-,=,140.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2529,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Potasio,-,=,1.600,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2530,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Sodio,-,=,14.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2531,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Residuo seco,-,=,598.000,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2532,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Conductividad,-,=,817.000,µS/cm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2533,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),pH,-,=,7.400,U. pH.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2534,SC62,02/02/2022,09:40,MANANTIALES,Aguas (Fisicoquímica),Ortofosfato,-,<,0.031,mg/l,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df_sample[df_sample["Code"] == "SC62"]

Empty DataFrame
Columns: [Code, Sample Point, Type, Territory, Municipality, XETRS89, YETRS89, ZETRS89, Water range, Water range type, Basin, Section, Subgroup]
Index: []