# Ejercicio 1
En este ejercicio vas a realizar un programa ya algo más complejo, en el que tendrás que utilizar clases, bucles, listas, input y módulos de Python. Vas a trabajar con datos reales, de las estaciones de bicicleta de *BiciMAD*. Necesitarás implementar un par de clases para modelizar tus datos. Además, el programa que diseñes será interactivo y le pedirá al usuario ciertos inputs.

Necesitas 3 script que irán en el mismo directorio:
1. main.py
2. clases.py
3. funciones.py

El script que tendrás que ejecutar para que funcione tu programa será "main.py". Ya tienes un código hecho (abajo) que lee los datos de bicimad y los añade a un DataFrame de pandas. Ese sería el inicio del programa. **Asegúrante que tienes en el mismo directorio el archivo "2018_Julio_Bases_Bicimad_EMT.xlsx"**.

Puedes, o bien desarrollar el ejercicio en la propia carpeta del día de clase, o crearte una carpeta en otro lugar del ordenador.

¿Qué debería llevar cada archivo?

### clases.py
En este script diseñarás tus clases, que luego importarás en otro script para crear tus objetos personalizados. Tienes que implementar dos clases:

#### clase Estacion
Con esta clase podrás crear tus objetos de tipo `Estación`, los cuales tendrán ciertas propiedades como su nombre o ubicación, y alguna que otra función útil.

Necesitas crear un __init__ de este estilo:
```Python
def __init__(self, name, identificador, num_bicis, address, longitude, latitude)
```
**Rellena el resto del __init__**

Y un método `distancia` que ya te doy hecho. Este método calcula la distancia entre la estación de ese objeto (que tiene asociadas una latitud y una longitud) con la latitud y longitud que introduzcamos. El output es en km.

```Python
def distancia(self, latitude, longitude):

    lat1, lon1 = self.latitude, self.longitude
    lat2, lon2 = latitude, longitude
    radius = 6371  # km

    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) * math.sin(dlat / 2) +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) * math.sin(dlon / 2))
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    d = radius * c

    return d
```        
        
#### clase ComunidadMadrid
Esta clase debe tener lo siguiente:
* Un __init__ con un único parámetro de entrada, que serán las `estaciones`. Cuando crees un objeto de esta clase tendrás que introducir como argumento de entrada una lista cuyo contenido sean todo objetos de tipo `Estacion`.
* Un método `get_ids(self)`, sin parámetros de entrada, que devuelva una lista con todos los identificadores de estación en formato `int`.
* Otro método, `busca_estacion(self, estacion, tipo_busqueda)`, que busque el parámetro de entrada `estacion`, dentro de las estaciones del objeto ComunidadMadrid. El tipo de búsqueda puede ser por "id", en ese caso buscará entre los identificadores de estación, o puede ser por "name", en cuyo caso buscará si el parámetro de entrada `estacion` está contenido en el nombre de alguna de las estaciones. Si no encuentra la estación, devuelve `None`, y si la encuentra, devuelve el objeto estación completo.

### funciones.py
Implementa una función que tenga las siguientes características:
* Nombre: `dist_estaciones`
* Input: (est1, est2, comunidad). Son dos objetos de tipo `int`, con dos indentificadores de estación, y otro de tipo `ComunidadMadrid`.
* Output: la distancia entre ambas estaciones.

### main.py
El script main tiene que ser un programa interactivo que vaya preguntando al usuario. Vamos paso a paso:
* Importa tus clases y funciones al principio del script
* Descomenta las líneas de código que hay tras el importado de datos, de manera que crees una lista con todas las estaciones, con sus datos.
* Crea un objeto llamado `comunidad`, que sea de tipo `ComunidadMadrid`
* Lo que viene a partir de ahora es un `while True:`. Que se ejecutará siempre, a no ser que en algún punto del `while` haya un `break`. Ahora vemos dónde ponerlo.
* Al principio del `while` hay que preguntar al usuario qué desea hacer, mediante un menú sencillo:

    Escoge una opcion: 
    1. Busca estacion (nombre)
    2. Calcula distancia (entre ids)
    3. Salir del programa
    
Son las tres opciones que tiene el usuario para introducir: 1,2,3

* **Si introduce 3**: Pon un mensaje de despedida y sal del `while`. Aquí va el `break`! Te recomiendo que empieces por aquí para que no se te quede el `while` en un bucle infinito. Asegúrate que el menú funciona bien y después implementa las funcionalidades de cada opción.

* **Si introduce 1**: tienes que buscar la estación (por nombre) entre todas las estaciones del objeto `comunidad`. Si la encuentras, imprime por pantalla su nombre, preguntale al usuario "¿Qué más deseas hacer?", y que el programa vuelva al menú con las tres opciones. Si no la encuentra, ponlo también por pantalla con un print, y que el programa vuelva al menú.

* **Si introduce 2**: hay que pedirle al usuario dos inputs, que serán dos enteros con los dos ids de estación. Con esos ids calcula la distancia entre ambas estaciones.

* **En cualquier otro caso**: imprime por pantalla que la respuesta no es valida, y vuelve al menu inicial.

In [1]:
import pandas as pd

df = pd.read_excel("2018_Julio_Bases_Bicimad_EMT.xlsx")

'''
tot_est = []
for index, row in df.iterrows():
    estacion = Estacion(row[0], row[3], row[1], row[6], row[4], row[5])
    tot_est.append(estacion)
'''

'\ntot_est = []\nfor index, row in df.iterrows():\n    estacion = Estacion(row[0], row[3], row[1], row[6], row[4], row[5])\n    tot_est.append(estacion)\n'

In [2]:
df.head()

,name,total_bases,number,id,longitude,latitude,address
0,Agustín de Betancourt,24,134,153,-3.695605,40.444030,Calle María de Guzmán nº 58
1,Alberto Alcocer,24,158,138,-3.684715,40.458532,Avenida de Alberto Alcocer nº 22
2,Alcalá,27,97,102,-3.680131,40.422691,Avenida de Menéndez Pelayo nº 3
3,Alcántara,24,99,104,-3.673871,40.426185,Calle Alcántara nº 2
4,Almadén,24,67,71,-3.693225,40.410847,Calle Almadén nº 28