# Ex2 - Filtering and Sorting Data

Esta vez vamos a sacar los datos directamente de Internet.

### Paso 1. Importar las librer√≠as necesarias

In [1]:
import pandas as pd
import numpy as np

### Paso 2. Importar el conjunto de datos de este [site](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

### Paso 3. Asignarlo a una variable llamada euro12.

In [2]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
# euro12 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv')
euro12 = pd.read_csv('Euro_2012_stats_TEAM.csv')
euro12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

In [3]:
euro12.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     object
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     object
 5   % Goals-to-shots            16 non-null     object
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     object
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     object
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB

In [4]:
euro12.describe(include='all')

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
count,16,16.000000,16.000000,16.000000,16,16,16.000000,16.000000,16.000000,16.0000,16.000000,16.000000,16.000000,16,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,15.000000,16.00000,16.000000,16.000000,16.000000,16,16.000000,16.000000,16.000000,16.000000,16.000000,16.00000,16.00000,16.000000
unique,16,NaN,NaN,NaN,15,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Croatia,NaN,NaN,NaN,50.0%,16.0%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.9%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.7%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,4.750000,17.125000,24.937500,NaN,NaN,54.937500,1.250000,0.187500,0.0625,1.375000,1763.375000,1467.375000,NaN,2579.187500,57.187500,52.312500,21.562500,68.375000,86.375000,63.562500,0.333333,1.06250,12.562500,4.750000,12.125000,NaN,52.937500,55.625000,8.125000,7.437500,0.187500,10.87500,10.87500,17.250000
std,NaN,2.886751,10.582218,10.680005,NaN,NaN,26.065223,1.612452,0.403113,0.2500,1.024695,906.177898,827.580721,NaN,1122.164707,18.616189,22.703065,11.236659,22.823599,24.611312,25.765529,0.617213,1.28938,6.937519,1.983263,4.573474,NaN,22.915697,18.973227,4.910872,3.265348,0.403113,3.53789,3.53789,1.527525
min,NaN,1.000000,7.000000,10.000000,NaN,NaN,27.000000,0.000000,0.000000,0.0000,0.000000,851.000000,606.000000,NaN,1433.000000,33.000000,18.000000,7.000000,34.000000,41.000000,29.000000,0.000000,0.00000,4.000000,1.000000,6.000000,NaN,25.000000,30.000000,2.000000,4.000000,0.000000,7.00000,7.00000,15.000000
25%,NaN,2.750000,9.750000,18.000000,NaN,NaN,36.500000,0.000000,0.000000,0.0000,0.750000,1190.750000,951.500000,NaN,1856.250000,43.750000,37.250000,14.000000,54.250000,73.750000,44.500000,0.000000,0.00000,8.000000,3.000000,9.750000,NaN,35.750000,44.500000,4.000000,5.000000,0.000000,8.50000,8.50000,16.000000
50%,NaN,4.500000,13.000000,23.500000,NaN,NaN,44.000000,1.000000,0.000000,0.0000,1.500000,1522.000000,1211.500000,NaN,2220.500000,53.500000,51.000000,19.500000,65.000000,85.000000,58.500000,0.000000,1.00000,10.000000,5.000000,11.000000,NaN,45.500000,51.000000,7.500000,6.500000,0.000000,10.50000,10.50000,17.000000
75%,NaN,5.250000,22.000000,32.250000,NaN,NaN,68.750000,2.000000,0.000000,0.0000,2.000000,1934.750000,1546.500000,NaN,2921.250000,62.250000,65.000000,28.500000,80.000000,99.000000,73.750000,0.500000,1.25000,13.500000,6.000000,13.500000,NaN,64.000000,64.750000,11.250000,9.000000,0.000000,12.50000,12.50000,18.250000
max,NaN,12.000000,42.000000,45.000000,NaN,NaN,110.000000,6.000000,1.000000,1.0000,3.000000,4317.000000,3820.000000,NaN,5585.000000,101.000000,106.000000,44.000000,122.000000,137.000000,136.000000,2.000000,5.00000,29.000000,9.000000,22.000000,NaN,102.000000,90.000000,19.000000,16.000000,1.000000,18.00000,18.00000,20.000000

### Paso 4. Selecciona s√≥lo la columna de Goal.

In [5]:
# euro12.Goals
# euro12['Goals']
euro12[['Goals']]

    Goals
0       4
1       4
2       4
3       5
4       3
5      10
6       5
7       6
8       2
9       2
10      6
11      1
12      5
13     12
14      5
15      2

### Paso 5. ¬øCu√°ntos equipos participaron en la Euro2012?

In [6]:
len(euro12)
# euro12['Team'].shape

16

In [7]:
len(euro12['Team'].unique())

16

In [8]:
euro12['Team'].nunique()

16

In [ ]:
# euro12.index

### Paso 6. ¬øCu√°l es el n√∫mero de columnas del conjunto de datos?

In [9]:
len(euro12.columns)

35

In [10]:
euro12.shape[1]

35

### Paso 7. Qu√©date s√≥lo las columnas Equipo, Tarjetas Amarillas y Tarjetas Rojas y as√≠gnalas a un dataframe de datos llamado discipline

In [11]:
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [12]:
discipline = euro12.loc[:, ['Team', 'Yellow Cards', 'Red Cards']]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [13]:
discipline = pd.DataFrame(euro12, columns=["Team", "Yellow Cards", "Red Cards"])
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

### Paso 8. Ordena los equipos por tarjetas rojas y luego por tarjetas amarillas

In [ ]:
# list(discipline.sort_values(['Red Cards'], ascending = False)['Red Cards'].values)

In [14]:
discipline.sort_values(['Red Cards', 'Yellow Cards'], ascending = [False, False])

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

### Paso 9. Calcula la media de tarjetas amarillas por equipo

In [15]:
discipline['Yellow Cards'].mean()

7.4375

### Paso 10. Filtrar los equipos que han marcado m√°s de 6 goles

In [16]:
euro12[euro12['Goals']>6][['Team','Goals']]

       Team  Goals
5   Germany     10
13    Spain     12

### Paso 11. Seleccione los equipos que empiezan por G

In [17]:
euro12[euro12['Team'].str[0]=='G']

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20

In [18]:
euro12[euro12['Team'].str.startswith('G')]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20

### Paso 12. Selecciona las 7 primeras columnas

In [19]:
euro12.iloc[:, 0:7]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked)
0,Croatia,4,13,12,51.9%,16.0%,32
1,Czech Republic,4,13,18,41.9%,12.9%,39
2,Denmark,4,10,10,50.0%,20.0%,27
3,England,5,11,18,50.0%,17.2%,40
4,France,3,22,24,37.9%,6.5%,65
5,Germany,10,32,32,47.8%,15.6%,80
6,Greece,5,8,18,30.7%,19.2%,32
7,Italy,6,34,45,43.0%,7.5%,110
8,Netherlands,2,12,36,25.0%,4.1%,60
9,Poland,2,15,23,39.4%,5.2%,48
10,Portugal,6,22,42,34.3%,9.3%,82
11,Republic of Ireland,1,7,12,36.8%,5.2%,28
12,Russia,5,9,31,22.5%,12.5%,59
13,Spain,12,42,33,55.9%,16.0%,100
14,Sweden,5,17,19,47.2%,13.8%,39
15,Ukraine,2,7,26,21.2%,6.0%,38

### Paso 13. Selecciona todas las columnas excepto las 3 √∫ltimas

In [20]:
euro12.iloc[:, :-3]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0

### Paso 14. Presenta s√≥lo la Shooting Accuracy de Inglaterra, Italia y Espa√±a

In [21]:
euro12.loc[[3,7,12],['Team','Shooting Accuracy']]

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%

In [ ]:
# indices = euro12[euro12['Team'].isin(['England','Italy','Russia'])].index

# euro12.loc[indices,['Team','Shooting Accuracy']]

In [24]:
euro12[euro12['Team'].isin(['England','Italy','Russia'])][['Team','Shooting Accuracy']]

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%

In [29]:
df_new = euro12.set_index('Team')
df_new.loc[['England','Italy','Russia'],['Shooting Accuracy']]

        Shooting Accuracy
Team
England             50.0%
Italy               43.0%
Russia              22.5%